# Generated by Django 5.2.7 on 2025-11-12 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la salle')),
                ('capacite', models.IntegerField(verbose_name='Capacité')),
                ('equipements', models.TextField(verbose_name='Équipements disponibles')),
                ('etage', models.IntegerField(verbose_name='Étage')),
                ('image_url', models.URLField(blank=True, verbose_name="URL de l'image")),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date', models.DateField(verbose_name='Date de réservation')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('motif', models.TextField(verbose_name='Motif de la réservation')),
                ('nombre_participants', models.IntegerField(verbose_name='Nombre de participants')),
                ('validee', models.BooleanField(default=True, verbose_name='Validée')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Salles.salle', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date', '-heure_debut'],
            },
        ),
    ]
